### ISSUE TITLE
bands.levelDelta is optional

### ISSUE THREAD

**Issue by kakopappa** [sinricpro/nodejs-sdk#1]
Just found out that bands.levelDelta is optional. please make sure it's handled properly in node/python

https://github.com/sinricpro/sample_messages/blob/master/19_AdjustBands/01_Request.json

**Comment by thegoliathgeek** [comment]
Okay. I'll first check if the delta is defined in the request, if defined i'll consider it.

**Comment by kakopappa** [comment]
According to this

https://developer.amazon.com/docs/device-apis/alexa-equalizercontroller.html


It’s optional
