### ISSUE TITLE
Connection seems to be lost after some time

### ISSUE THREAD

**Issue by SteffenKn** [sinricpro/nodejs-sdk#11]
I have a few devices that I control via Alexa. The programs all run 24/7.
After some time (a few hours to days) the connection seems to get lost. Then the devices no longer respond to voice commands and Alexa just says "device xy is not responding".
Here is an example of my implementation: https://github.com/SteffenKn/WS2801-alexa/blob/develop/src/alexa-device-handler.ts

**Comment by kakopappa** [comment]
@imdhanush  seems we need a WebSocket disconnection callback similar to https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Switch/Switch/Switch.ino#L112 to detect disconnections from the server

**Comment by thegoliathgeek** [comment]
Please refer to this [example](https://github.com/sinricpro/nodejs-sdk/blob/6de083fde1f24217e2f5c7d1c7fbf74991816f73/examples/light-bulb/light-bulb.js#L34).
Update the sdk to the latest version.

**Comment by SteffenKn** [comment]
I have tested this for a few days and it seems to work.
Thanks for the quick fix.
