### ISSUE TITLE
"Alexa turn off thermostat" sometimes sets Mode to OFF

### ISSUE THREAD

**Issue by emnik** [sinricpro/nodejs-sdk#38]
When PowerController state is on, sometimes the directive "Alexa turn off thermostat results to setting the MODE to OFF instead off PowerController to off!
It should not!
Mode OFF should happen when I say "Alexa set thermostat mode to OFF"...

**Comment by kakopappa** [comment]
Hi @emnik this is the behavior of Alexa. This is out of our control

**Comment by emnik** [comment]
hmm... thought so! Thank you for your response!
