### ISSUE TITLE
Invalid Event: setThermostatMode

### ISSUE THREAD

**Issue by emnik** [sinricpro/nodejs-sdk#39]
raiseEvent(sinricpro, eventNames.thermostatMode, 'DeviceId', { thermostatMode: 'HEAT' });
results in:
Invalid Event: setThermostatMode

**Comment by kakopappa** [comment]
Hi @emnik  I have fixed this in the latest version of the sdk (2.9.1). it may take some time to pop in npm so please 

`const actionArr = ['setPowerState', 'setBrightness', 'setPowerLevel', 'setColor', 'setColorTemperature', 'DoorbellPress', 'currentTemperature', 'pushNotification'];`

to

`const actionArr = ['setPowerState', 'setBrightness', 'setPowerLevel', 'setColor', 'setColorTemperature', 'DoorbellPress', 'currentTemperature', 'pushNotification', 'setThermostatMode'];`

in `lib/events/event_handler.js` in your local sinricpro library. it's inside `node_modules`

**Comment by emnik** [comment]
@kakopappa OK setThermostatMode now works! Thank you!!!
